### ISSUE TITLE
Publish Single File cause bug in PreloadLibrary

### ISSUE THREAD

**Issue by d3c0d3d** [stride3d/stride#1094]
**Release Type**: Official Release

**Version**: Stride 4.1.0.1459-beta (from nuget)

**Platform(s)**: Windows

**Describe the bug**
I used the default template to create a game in third person to test the publication of a single executable but when I run the compilation nothing happens, when investigating the event log to windows I managed to catch the following error message:
```
Application: ThirdPersonGame.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Rendering.BackgroundCubemapShaderKeys' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Core.Native.NativeInvoke' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Stride.Core.NativeLibraryHelper.PreloadLibrary(String libraryName, Type owner)
   at Stride.Core.Native.NativeInvoke..cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.Native.NativeInvoke.Setup()
   at Stride.Native.Module.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.Stride_GraphicsSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Rendering.BackgroundCubemapShaderKeys..cctor()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(RuntimeTypeHandle type)
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.Serialization.AssemblyScan.Stride_EngineAssemblyScan.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.ThirdPersonGameSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
```
apparently in "Preload Library" it is trying to load something to disk but this is not valid for a single file application this causes the silent error.

**To Reproduce**
Reproduction is very simple, just create a project using the third-person template then in visual studio configure the release publication to a single and self-sufficient file executable.

**Expected behavior** Run the game perfectly!

**Comment by manio143** [comment]
I had that issue and fixed it in #1068 - so unless something has changed it should be fixed on master

**Comment by d3c0d3d** [comment]
@manio143 Thanks for your feedback. 
I was using the Stride package from nuget apparently he it still doesn't have your fix #1068, I'm going to try using it from the stride3d:master now to see if it solves my problem, thanks!

**Comment by manio143** [comment]
@d3c0d3d Is there still an issue or can we close this?

**Comment by d3c0d3d** [comment]
@manio143 I managed to solve my issue by downloading all the source code and compiling and generating a new local package, the current package that is in nuget (4.1.0.1459-beta) still has the problem so I didn't close this issue as a reminder! but you are free if you want to close it!

**Comment by Eideren** [comment]
I'll close this one off before we forget about it, fixed in #1068
