### ISSUE TITLE
Poor scene editor performance when the prefab editor is open in background

### ISSUE THREAD

**Issue by crystalboxes** [stride3d/stride#353]
**Release Type**: GitHub

**Version**: 3.1.0.1-beta01

**Platform(s)**: Windows

**Describe the bug**
Scene editor becomes sluggish (unresponsive at times) when the prefab editor tab is open (in background).

**To Reproduce**
1. Open scene asset.
2. Open prefab asset.
3. Switch to scene editor.
4. Try to navigate, orbit/pan in the viewport.

![xenko gamestudio_2019-01-30_01-01-44](https://user-images.githubusercontent.com/11932586/51946587-a8290e00-242a-11e9-8244-a16ba89b7301.png)

**Expected behavior**
Poor frame rate in the scene editor, navigation actions keep working when mouse is released making the editor unusable.

**Comment by Kryptos-FR** [comment]
For comparison purpose, could you tell us more about your machine configuration? Laptop/desktop, OS version, CPU, RAM, GPU (esp. integrated vs dedicated card), available disk space, etc.

**Comment by crystalboxes** [comment]
Sure.
Desktop
Windows 10 Pro
i7-4790k
32GB RAM
GTX 1080ti as a main card + GTX 980 as a secondary card
~50 GB available on the system drive.

**Comment by xen2** [comment]
Should be fixed with #359.
@crystalboxes can you let us know if it works better with latest master?

**Comment by phr00t** [comment]
After building with #359, I still experience this problem. When I have a UI editor tab open (but not in focus), the editor performance staggers when moving & looking around. If I close the UI editor tab, the editor seems to operate smoothly. I'd consider this problem not fixed.

**Comment by FailMelon** [comment]
Still an issue in 3.1.0.1-beta02-0615

**Comment by phr00t** [comment]
@FailMelon try my fork, where I've made changes that seem to have improved this significantly https://github.com/phr00t/xenko

**Comment by Eideren** [comment]
Should have been fixed through #612, feel free to open a new one if you still have issues with this.
